### ISSUE TITLE
copy & paste error?

### ISSUE THREAD

**Issue by WegoW** [RoonLabs/node-roon-api-browse#1]
These 2 lines at the end look like a copy & paste error. Right?

};
};

**Comment by dannyfiresnake** [comment]
fixed bbc35c3

this api is very hard to use and/or understand as it stands... i have comprehensive documentation, but it really needs to be jsdocified... up to the challenge? :-)

note, i just did this for https://roonlabs.github.io/node-roon-api-transport/RoonApiTransport.html
